version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "qa"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "qa"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
